name: StargateMapper
version: ${project.version}
main: org.sgrewritten.stargatemapper.StargateMapper
api-version: 1.13
description: An integration addon for Stargate Rewitten that adds support for mapping plugins
depend:
  - Stargate
softdepend:
  - dynmap
  - pl3xmap
  - squaremap
