name: SG-Dynmap
version: ${project.version}
main: com.ghostchu.stargatemapper.StargateDynmap
api-version: 1.13
description: StargameDynmap plugin
depend:
  - Stargate
softdepend:
  - dynmap
  - pl3xmap
  - squaremap
